# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import honeybee_pb2 as honeybee__pb2


class RunRecipeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.run = channel.unary_unary(
        '/honeybee.recipe.RunRecipe/run',
        request_serializer=honeybee__pb2.SolarAccessRecipeGridBased.SerializeToString,
        response_deserializer=honeybee__pb2.Result.FromString,
        )


class RunRecipeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def run(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RunRecipeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'run': grpc.unary_unary_rpc_method_handler(
          servicer.run,
          request_deserializer=honeybee__pb2.SolarAccessRecipeGridBased.FromString,
          response_serializer=honeybee__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'honeybee.recipe.RunRecipe', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
